compute_environment: LOCAL_MACHINE
deepspeed_config:
 gradient_clipping: 0.5
 offload_optimizer_device: none
 offload_param_device: none
 zero3_init_flag: false
 zero_stage: 1
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: 49502
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 4
use_cpu: false